### PR TITLE
snackbar bottom offset option in IOS

### PR DESCRIPTION
**Pull request by johandrott**
Created an option to allow bottom offset for a snackbar in IOS. This comes into play when you want to display the snackbar above a bottom navigation bar for example. There is no equivalent option for Android instead the view property should be used as described in the android snackbar documentation (https://developer.android.com/reference/com/google/android/material/snackbar/Snackbar#make)

### CODE REVIEW

**Comment by farfromrefug** [comment]
@johandrott thanks for that. I will have to look at this. I dont remember if i implemented the view option for ios. Would be the best way as it would be the same on ios/android

**Comment by johandrott** [comment]
I agree that a consistent option for both android and ios would be preferable. But after reading the documentation, setBottomOffset is the recommended way. At least for when wanting to display the snackbar above a bottom navigation bar. 

> This is meant for apps which have a navigation element such as a tab bar, which cannot move and should not be obscured.
(https://material.io/develop/ios/components/snackbars/api-docs/Classes/MDCSnackbarManager.html#/c:objc(cs)MDCSnackbarManager(im)setBottomOffset:)

There is no implementation of the view option on IOS but a call to setPresentationHostView should do the trick. I can play around with it and see if I can get it to work.

**Comment by johandrott** [comment]
@farfromrefug Implementing the view option on IOS was easy and I got it to work right away by just passing in the nativeView that I wanted to attach the snackbar to. But when I'm trying the same thing on android the snackbar is always shown at the bottom of the page, not respecting the container view. Do you have an example of using the view option on android? When reading the android documentation it talks about using a CoordinatorLayout as parent but there is no such layout element in nativescript.

**Comment by farfromrefug** [comment]
@johandrott i just released a new update with `view` option working for ios and android.
There might be edge cases but that seems good for now.
I will close that PR. If at any point you want to bring back the offset both for iOS and Android, please create a new PR.
Thanks for your work!

PS: your PR had some linting changes. Next time make sure to follow the linting rule of the project (see eslint config file)

**Pull request closed without merging**
