### PR TITLE
Improve Vue integration + Vue demo (WIP)

### PR DESCRIPTION
**Pull request by msaelices**
It's a Work In Progress as the core components are WIP too.

Related to #3.

### CODE REVIEW

**Comment by farfromrefug** [comment]
@msaelices I have a small issue with the require path of the material components from the install Vue function.
You use ```../..``` but this can be an issue in dev env where i [use aliases](https://github.com/Akylas/nativescript-material-components/blob/master/demo/webpack.config.js#L59) to find the material component.
This is quite important for me as it makes dev much faster.
Is there a reason why you changed from ```nativescript-material-ripple``` for example?

Need to try the v-model, i don't see how it could work without the fix in ```nativescript-vue```.

**Comment by farfromrefug** [comment]
@msaelices the vue demo example should use vue files. It actually behaves the same but is compiled differently by webpack.
Using ```template``` as you did, the templates are compiled in ```bundle.js``` as xml and thus parsed on runtime. This is why your v-model example works.

Now if you use ```vue``` files with an updated ```webpack.config.js``` as i use [here](https://github.com/cairn-monnaie/CairnMobile/blob/master/webpack.config.js), the ```.vue``` (which are XML) are actually compiled and the templates end up being JSON data in the ```bundle.js```.
This is where https://github.com/nativescript-vue/nativescript-vue/issues/371  appears

**Comment by msaelices** [comment]
> @msaelices I have a small issue with the require path of the material components from the install Vue function.
> You use `../..` but this can be an issue in dev env where i [use aliases](https://github.com/Akylas/nativescript-material-components/blob/master/demo/webpack.config.js#L59) to find the material component.

I've adapted the webpack here https://github.com/Akylas/nativescript-material-components/commit/eb0f3008bf1433adbec4b333891b034014d451c5 but I had two problems, with the `*/vue/index.ts` files when executing `tns run android --bundle --env.development`:

First of all, the `require('./..')` sentences, which worked with the `npm run tsc` command,  does not work and the `ts-loader` was unable to import the file. I think I've fixed it here: https://github.com/Akylas/nativescript-material-components/commit/338575d0ddd621ad60e21557346ee7e6e1253f28

When the `ts-loader` was "capable" of finding the files, there was another problem and the app was not working in most of the samples:

captura de pantalla 2019-01-22 a las 18 59 15

Without the `--env.development` param is working well.

> This is quite important for me as it makes dev much faster.
> Is there a reason why you changed from `nativescript-material-ripple` for example?
> 
> Need to try the v-model, i don't see how it could work without the fix in `nativescript-vue`.

**Comment by msaelices** [comment]
@farfromrefug I finally fix the issue with this hack: https://github.com/Akylas/nativescript-material-components/commit/f5525eb0936f3178c5f74f168929f63f895acdf1

**Comment by farfromrefug** [comment]
@msaelices so everything working for you?

**Comment by msaelices** [comment]
@farfromrefug yes, but I still need to refactor the demo Components into `.vue` files.

**Comment by msaelices** [comment]
@farfromrefug tslint errors fixed here: https://github.com/Akylas/nativescript-material-components/pull/2/commits/7f7b3a0c2ad3a91d381e56d5719fe3ee68390238

**Comment by msaelices** [comment]
@farfromrefug as the https://github.com/nativescript-vue/nativescript-vue/issues/371 is still pending, and because the current demo-vue is using Typescript, I would consider using `Component` classes instead of `.vue` files here.

With TS there is no need of using `.vue` files. Don't you prefer this kind of components? https://github.com/Akylas/nativescript-material-components/commit/61f5545d17531c78c7d8ff3ee9709bfdb86be138

**Comment by farfromrefug** [comment]
@msaelices well seeing we will need to test for the issue and seeing ```.vue``` files gives you better syntax color / typings... in VSCode, i would prefer .vue files. 
Also seeing that templates are parsed at runtime with ```.ts``` and template XML, it would be better to show that it is better to use ```.vue``` (will be faster at runtime).

Does it make a big difference for you?

**Comment by msaelices** [comment]
@farfromrefug my only concern is that v-model would not work ;)

**Comment by farfromrefug** [comment]
@msaelices yes it would not for now. We can fork and use the fork for now. I am actually thinking of doing it as ```nativescript-vue``` development is not really moving

**Comment by msaelices** [comment]
@farfromrefug I'm part of the `nativescript-vue` core team, but I would prefer to wait for the Rigor's suggestion, as he is the Author and by far the main developer.

**Comment by farfromrefug** [comment]
@msaelices i totally understand. But exporting ```registerElement``` is a fast solution which does not have any consequence. And it would allow this module and all other projects (like all my apps) to go on with custom modules ```v-model```. I would love to see that kind of fixes being faster released in ```nativescript-vue```

**Comment by msaelices** [comment]
@farfromrefug could you PTAL?

**Comment by farfromrefug** [comment]
What is PTAL?

**Comment by msaelices** [comment]
@farfromrefug PTAL means "Please Take Another Look" :)

**Comment by farfromrefug** [comment]
@msaelices can you make a release of ```nativescript-vue``` so that i can test your work on the demo?
Thanks

**Comment by msaelices** [comment]
@farfromrefug sorry but unfortunately I don't have the NPM permissions for releasing a new version. @rigor789 does.

**Comment by farfromrefug** [comment]
@msaelices looked at the sample app. I see 2 issues right now on iOS:
- the app crashes when running the progress bar example
- in the buttons example the "falseFab" is not rounded (class falseFAb not used?)

It works fine in the```demo``` app.

BTW i run the sample using ```tns run ios --bundle --env.development``` to use src instead of published packages.

**Comment by msaelices** [comment]
@farfromrefug the crash on the progress bar sample has been fixed here: https://github.com/Akylas/nativescript-material-components/pull/2/commits/c25a598a031fa7777fde1e144e67d27345f0154a

I cannot reproduce the second issue, as I see rounded borders in the `falseFab` button:

captura de pantalla 2019-02-01 a las 17 57 08

**Comment by farfromrefug** [comment]
You see it right! I dont see it that way. Will run again and report

**Pull request merged**
