### PR TITLE
Fix/bottomsheet ios resizing

### PR DESCRIPTION
**Pull request by alexander-mai**
The bottomsheet was not correctly resized while rotating from portrait to landscape.
The bottom sheet is now always using the full screen width on resize like it is doing when opening it in the disired orientation.
The child is informed about the resizing before it will render itself. When the child height is dependent on its width (fixed ration), it was not able to resize correctly, because it was only rendered before the parent (bottomsheet) was resized.

### CODE REVIEW

**Comment by farfromrefug** [comment]
@alexander-mai thanks! there are actually a lot of changes there. Will have to test that all.
Will let you know. Thanks

**Comment by alexander-mai** [comment]
Hello @farfromrefug,
what do you think when you can process my pull requests?

**Comment by farfromrefug** [comment]
@alexander-mai your PR broke a lot of thing. Safe area are not handled correctly anymore.
I will try and handle what you want to right way.
plus it needs to be optional. I kind of like the not full width in landscape

**Comment by alexander-mai** [comment]
Hello @farfromrefug,
I tried this on iPhone with and without Safe areas. The flags for bottom and top safe areas are handled correctly in my app and in demo app.
The full with on landscape ios zthe same behaviour like the current implementation.
The difference is, that on current implementation the width will not be resized correctly.
When opend in Landscape, the bottomsheet is opened in full width. After rotating to portrait, the width is reduced to the device width. After rotating back to landscape, the width still remains on portrtait width.

**Comment by farfromrefug** [comment]
@alexander-mai testing you PR everything was out of place and options to ignore safe areas were not working anymore.

And yes i do see the issue you are talking about. And it is a real issue somewhere else. The safe area size returned is not always correct. For now i dont see an easy fix. I tried a few things without success. I will have to look deeper into this.

**Pull request closed without merging**
